manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: love-444
      url-base: https://github.com/love-444
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-babopad
      remote: love-444
      revision: main
  self:
    path: config
     